import type { SchemaMetadata } from '../schema/types';
import { generateInterfaces } from './generateInterfaces';
import { generateDelegates } from './generateDelegates';

function lowerFirst(name: string): string {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

function generateClientClass(models: Array<{ name: string }>): string {
  const delegateProps = models
    .map((m) => `  public ${lowerFirst(m.name)}!: ${m.name}Delegate;`)
    .join('\n');
  const assignments = models
    .map(
      (m) => `    this.${lowerFirst(m.name)} = new ${m.name}Delegate(this.db);`,
    )
    .join('\n');

  return `export class SheetORMClient {
  private adapter: GoogleSheetsAdapter;
  private db!: Database;

${delegateProps}

  constructor(config: ClientInitializerGoogle) {
    this.adapter = new GoogleSheetsAdapter(config.credentials, config.sheetId);
    this.db = new Database(_schema, this.adapter);
  }

  async connect(): Promise<void> {
    await this.adapter.connect();

${assignments}
  }
}`;
}

export function generateClientCode(schema: SchemaMetadata): string {
  const models = Object.values(schema.models);
  if (models.length === 0) return '';

  const parts: string[] = [];

  parts.push('// Auto-generated by open-sheets-orm. Do not edit manually.');
  parts.push(
    "import { Database, GoogleSheetsAdapter } from 'open-sheets-orm';",
  );
  parts.push("import type { ClientInitializerGoogle } from 'open-sheets-orm';");
  parts.push(`const _schema = ${JSON.stringify(schema, null, 2)} as const;`);
  parts.push(generateInterfaces(schema));
  parts.push(generateDelegates(schema));
  parts.push(generateClientClass(models));

  return parts.join('\n\n');
}
