import type { SchemaMetadata } from '../schema/types';
import { generateInterfaces } from './generateInterfaces';
import { generateDelegates } from './generateDelegates';

function lowerFirst(name: string): string {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

function generateClientClass(models: Array<{ name: string }>): string {
  const properties = models
    .map((m) => `  public ${lowerFirst(m.name)}: ${m.name}Delegate;`)
    .join('\n');
  const assignments = models
    .map((m) => `    this.${lowerFirst(m.name)} = new ${m.name}Delegate(db);`)
    .join('\n');

  return `export class SheetORMClient {\n${properties}\n\n  constructor(adapter: SheetsAdapter) {\n    const db = new Database(_schema, adapter);\n${assignments}\n  }\n}`;
}

export function generateClientCode(schema: SchemaMetadata): string {
  const models = Object.values(schema.models);
  if (models.length === 0) return '';

  const parts: string[] = [];

  parts.push('// Auto-generated by open-sheets-orm. Do not edit manually.');
  parts.push("import { Database, type SheetsAdapter } from 'open-sheets-orm';");
  parts.push(`const _schema = ${JSON.stringify(schema, null, 2)} as const;`);
  parts.push(generateInterfaces(schema));
  parts.push(generateDelegates(schema));
  parts.push(generateClientClass(models));

  return parts.join('\n\n');
}
